### ISSUE TITLE
Create a sponsor section in the main index page

### ISSUE THREAD

**Issue by lestrrat** [builderscon/conf.builderscon.io#112]
技術協力：
* ClubT
* Google Cloud Platform
* Github
* Hatena

それぞれロゴをつけて、カンファレンス毎のスポンサーみたいなデザインでの掲載をする

**Comment by lestrrat** [comment]
@richard-imaoka もし、できるようだったら、プリーズ。

**Comment by richard-imaoka** [comment]
はい、やります。

ロゴ収集は (もちろんClubTさんは私ですが) 別の人がやるのですか？

**Comment by lestrrat** [comment]
持ってた気もする… とりあえずまた午後にでも見ますので少々お待ちを。

**Comment by lestrrat** [comment]
https://storage.googleapis.com/media-builderscon-1248/system/clubT-600x600.png
https://storage.googleapis.com/media-builderscon-1248/system/gcp-600x600.png

**Comment by morizooo** [comment]
hatenaさんはここですね
https://mackerel.io/ja/brand-assets

**Comment by richard-imaoka** [comment]
ありがとうございます。indexページのスポンサーのデータ(ロゴURL、リンク先URL等)はapp.pyあたりにハードコードでよいでしょうか？

もし、octavのデータベースに入れるなら[ダミーなconference_idを作る](https://github.com/builderscon/octav/blob/87d57db4ca5cee04c7c64f68a2094a822476f197/octav/db/interface.go#L218L231)などしないといけないので、app.pyなどconf.builderscon.io側で格納したほうがいいかな、と。

**Comment by lestrrat** [comment]
ハードコードでー

**Comment by lestrrat** [comment]
https://storage.googleapis.com/media-builderscon-1248/system/github-600x600.png
https://storage.googleapis.com/media-builderscon-1248/system/mackerel-600x600.png
