### ISSUE TITLE
Add description to nav bar at top

### ISSUE THREAD

**Issue by richard-imaoka** [builderscon/conf.builderscon.io#125]
これだとわかりにくい
PC版で横に伸びすぎる問題は、伸びすぎたら考える…？

![image](https://cloud.githubusercontent.com/assets/7414320/18549066/293354c8-7b87-11e6-9903-e1b8fda0498f.png)

**Comment by lestrrat** [comment]
これ、全部`アイコン 名称`とかに統一する？それとも`名称`のみ？

**Comment by richard-imaoka** [comment]
わたし個人の意見としては、「名称のみでアイコンなし」の方がよいかなと思います。
名称あればアイコンはわざわざいらなそうですし、アイコンがある項目があったり無い項目があったりするのは変な感じかもしれません。
