### ISSUE TITLE
Strange behavior of proposal's language

### ISSUE THREAD

**Issue by hasegawa-tomoki** [builderscon/conf.builderscon.io#130]
プロポーザルの言語が当初指定していなかった言語で表示されていたかもしれない。
1. 10/3に、[セッション一覧]（https://builderscon.io/builderscon/tokyo/2016/sessions) で、自分のアイコンの下に「EN」と書いてあるのを発見。
2. あれ？と思って[詳細画面](https://builderscon.io/builderscon/tokyo/2016/session/befc0eaf-64d4-40e6-a190-c74d9ede2ad6) 見て見たら、使用言語、スライド言語ともに、英語になっていた。
3. 初回投稿時に日本語指定したはずだが…と、編集画面に行ったら英語になっていたので、日本語に指定しなおして保存した。
4. 一覧も詳細も正しく表示される様になった。
5. 他にも 初期応募の timakin さん、cho45 さんも、タイトルが日本語なのに対して、使用言語、スライド言語ともに英語表示されているので、初期応募のひとに何かが起きているのかもしれない。

**Comment by lestrrat** [comment]
多分なおってる
