### ISSUE TITLE
Overlapping nav bar with contents, for the sponsor and the news pages

### ISSUE THREAD

**Issue by richard-imaoka** [builderscon/conf.builderscon.io#29]
私が修正するつもりです(権限上自分にassignできないです)。

PCではnavバーと、コンテンツが重なっています。よろしくない。
![2016-07-23_22h30_59_m7u3sc](https://cloud.githubusercontent.com/assets/7414320/17084042/d43bd13c-51ee-11e6-9bea-1f144405dfa8.png)

Mobileでは同様の問題は発生していません。
![image](https://cloud.githubusercontent.com/assets/7414320/17084050/104812e4-51ef-11e6-9843-f7eb7574aa23.png)

**Comment by richard-imaoka** [comment]
PRマージされたのでクローズです！

**Comment by lestrrat** [comment]
次回からPRに `fixes $issue_number` って入れておくといいですよ。自動的にクローズされます。

**Comment by richard-imaoka** [comment]
なるほど、ありがとうございます！
