### ISSUE TITLE
change session datastore

### ISSUE THREAD

**Issue by lestrrat** [builderscon/conf.builderscon.io#4]
MySQLにセッションを入れるという苦行は行いたくないので、Redisでお願いします。`SETEX`で数時間のexpireをつけて保存。

**Comment by nasa9084** [comment]
redisを使うように変更しました。
```SETEX```を使う都合でトップレベルにキーとしてsession_id, バリューとしてusernameを入れています。

**Comment by nasa9084** [comment]
"数時間のexpireをつけて"を読み飛ばしていたので、expireの時間を7日間から5時間に変更しました。

**Comment by lestrrat** [comment]
まだimport MySQLが残ってないですか？
