### ISSUE TITLE
Speaker page

### ISSUE THREAD

**Issue by richard-imaoka** [builderscon/conf.builderscon.io#42]
Featured Speakerを目立たせる。

**Comment by lestrrat** [comment]
これはメモだけど、 Featured Speakerは「ユーザー登録をしていなくても、主催者が先に目立たせたい情報を入れておくための箱」なので、タイトルとミスマッチな気がする

**Comment by richard-imaoka** [comment]
これ最初はスピーカーの情報も載せたページが必要だな、とうすらぼんやり考えていたのですが、よくよく考えてみたら

 - #43 Sessions Page for a conferenceで「このカンファレンスのスピーカーの一覧」は「セッションの一覧」として載る
 - Featured Speakerはすでにスピーカーの説明書きとともにconference毎のページに出ている

ので、builderscon.io/builderscon/tokyo/2016/speakersみたいなページを作ってわざわざ表示する必用ってないです…よね？

ただ、カンファレンスごとではなく、スピーカー個人のページbuilderscon.io/speaker?id=*****というのを用意して、dashboardみたいに過去の投稿一覧が見られるというなら意味はありそうですが。

**Comment by richard-imaoka** [comment]
Ruby Kaigiは[スピーカーページ](http://rubykaigi.org/2016/speakers/)がありますね…顔写真と説明書きのみ。

YAPCとPHPConなども調べてみましたが、他では「セッション」ページと別に「スピーカー」ページをわざわざ作ってるのはあまりなさそうです。(Featured SpeakersはYAPCでも当然ありました。)

**Comment by lestrrat** [comment]
個別カンファレンスごとのスピーカーページは必要ないけど、builerscon全体を通してのスピーカーページなら必要ありますね。

あれ、これなんでプライオリティがhighなんだ。dashboardのつもりだったのかな＞自分

**Comment by richard-imaoka** [comment]
確認ありがとうございます、了解です。

**Comment by lestrrat** [comment]
大分前に作ってあった。
