### ISSUE TITLE
Query string lang=ja is gone when clicking a link on a page

### ISSUE THREAD

**Issue by richard-imaoka** [builderscon/conf.builderscon.io#44]
[https://conf.builderscon.io/builderscon/tokyo/2016?lang=ja](https://conf.builderscon.io/builderscon/tokyo/2016?lang=ja)
このページの例えばニュースをクリックすると

[https://conf.builderscon.io/builderscon/tokyo/2016/news](https://conf.builderscon.io/builderscon/tokyo/2016/news)
になってlang=jaが消える

[https://conf.builderscon.io/builderscon/tokyo/2016/news?lang=ja]
(https://conf.builderscon.io/builderscon/tokyo/2016/news?lang=ja)
に飛んでほしい

全部のa hrefを書き換えるのか？

**Comment by lestrrat** [comment]
`lang=`を指定するのはデバッグの時とかだけなので、いらないと思います。（普通はaccept-languageとかを見るか、一発クッキーをかますリンクを仕込んでおく）
