### ISSUE TITLE
Set OGP

### ISSUE THREAD

**Issue by lestrrat** [builderscon/conf.builderscon.io#46]
"知らなかったを、聞く"をOGPになんとか入れたい… が、これって日本語・英語の切り替えはできないんだよな。まぁ最低限でも "Discover Something New"は入れたい。

**Comment by richard-imaoka** [comment]
(assigned to meのつもりで見てました)
これもう完全に「切り替えできない」で答えが出てる問題ですかね？それとも切り替えの可能性をまだ調査中する話ですか？

調べてみたところ

 - [OGP internationalization]
(https://developers.facebook.com/docs/opengraph/guides/internationalization/)

- [非公式 Twittter 国際化](http://westplain.sakuraweb.com/translate/twitter/Best-Practices/Internationalization.cgi)

Facebook, Twitterは[Facebook翻訳](https://www.facebook.com/?sk=translations)と[Twitter翻訳](https://translate.twitter.com)を利用するため、「Discover Something New -> 知らなかったを、聞く」のような一般的な訳とは異なるものを登録できない、ってことだと思いました。

**Comment by lestrrat** [comment]
fb_localeを見ればいいのか
