### ISSUE TITLE
ビーコン君のページを作る

### ISSUE THREAD

**Issue by lestrrat** [builderscon/conf.builderscon.io#47]
必要な要素：

* 基本情報の掲示
* 基本素材の提供
* 著作権の掲示 (c) endeworks, (c) yassang 
* ライセンスの提示 CC-BY-NC 4.0 https://creativecommons.org/licenses/by-nc/4.0/

* 利用する際には 著作権表記は任意、ただし最低限 by yassangがあると嬉しい

**Comment by richard-imaoka** [comment]
作業はじめます、調査中です。

**Comment by richard-imaoka** [comment]
たたき台その1

hero_imageがあればもっと華やかになりそう

詳細はブログに書く？ただこっちにも、もうちょっと紹介を入れるべきでしょうか？

![image](https://cloud.githubusercontent.com/assets/7414320/17179413/17b03478-5454-11e6-8da2-75fb98ab4d18.png)


>The builderscon beaver, "Beacon" was designed by yassang. The copyright is held by © endeworks and © yassang, and the design is licensed under Creative Commons (CC BY-NC 3.0). When you show attribution upon using the design, it is up to you how you display the attribution as long as it is compliant with the license. However, we prefer you include "by yassang" in the attribution.

以下の定型句が日本語、英語両方にあれば使うべき→調べてます。

>When you show attribution upon using the design, it is up to you how you display the attribution as long as it is compliant with the license.

**Comment by lestrrat** [comment]
これはちょっとイメージが違うのでまず一回こちらで作業します！すみませんm(_ _)m
