### ISSUE TITLE
CFP page tabs for languages

### ISSUE THREAD

**Issue by richard-imaoka** [builderscon/conf.builderscon.io#93]
Instead of dropdown for title and abstract, check and see if tabs can be used for entering CFP in different languages.

http://foundation.zurb.com/apps/docs/#!/tabs

**Comment by richard-imaoka** [comment]
@lestrrat さんめっちゃ早かった、イシューあげるまでもなかったw
ありがとうございます。

**Comment by lestrrat** [comment]
こっちじゃないでしょ！

**Comment by richard-imaoka** [comment]
あ、こっちじゃない、すいません
